//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAppBar.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ListaProductos
    {
        public int idproducto { get; set; }
        public string nombre_producto { get; set; }
        public Nullable<decimal> precio_inicial { get; set; }
        public Nullable<decimal> precio_venta { get; set; }
    }
}
